### PR TITLE
csclient/params: add Channel and PublishRequest

### PR DESCRIPTION
**Pull request by rogpeppe**
Also update the test that relies on the old publish endpoint.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/161/
Test FAILed.

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/165/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/166/
Test PASSed.

**Comment by rogpeppe** [comment]
github seems to be confused. trying again.

**Pull request closed without merging**
