### PR TITLE
Preparation for splitting download stats on promulgation.

### PR DESCRIPTION
**Pull request by fabricematrat**

### CODE REVIEW

**Comment by rogpeppe** [comment]
LGTM

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/82/
Test PASSed.

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
