### PR TITLE
Fix development/edge migration leftovers.

### PR DESCRIPTION
**Pull request by frankban**
... and update dependencies to include the 4channels charm store.

### CODE REVIEW

**Comment by frankban** [comment]
Note that this is proposed against a feature branch.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/267/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
