### PR TITLE
csclient: fix resources requests to meet specification

### PR DESCRIPTION
**Pull request by rogpeppe**
We should upload resources with POST not PUT, and
we should upload and download resources from the same endpoint.
We standardise on /resource rather than /resources for that
endpoint.

Also, the Origin field should be set by the client, not the server,
as it does not make sense for the charm store
to be able to return origin=upload.

Also update dependencies and fix tests to cope with those.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/231/
Test FAILed.

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/232/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/233/
Test PASSed.

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
$$merge$$
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
