### PR TITLE
Update charmstore dependency (current 4channels feature branch).

### PR DESCRIPTION
**Pull request by frankban**
Also update the Resolve logic to be more agnostic when selecting the best channel.

### CODE REVIEW

**Comment by frankban** [comment]
Self review, trivial.
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/269/
Test FAILed.

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/charmrepo-merge/83

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/270/
Test PASSed.

**Comment by jrwren** [comment]
👍

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/271/
Test PASSed.

**Comment by urosj** [comment]
LGTM

**Comment by frankban** [comment]
Thanks for the rveiews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
