### PR TITLE
Updated the dependencies.tsv

### PR DESCRIPTION
**Pull request by vinu2003**
Updated the dependencies.tsv for charm Version feature

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmrepo/398/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmrepo/399/

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
