### PR TITLE
CharmStore: fix Get for Windows

### PR DESCRIPTION
**Pull request by rogpeppe**
Also added a comment to ensure that the Close call doesn't
get removed again.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/51/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:

**Comment by jrwren** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
