### PR TITLE
Rename variable to describe what it is.

### PR DESCRIPTION
**Pull request by kat-co**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/217/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/218/
Test PASSed.

**Comment by natefinch** [comment]
:+1:

**Comment by kat-co** [comment]
$$merge$$

**Comment by kat-co** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
