### PR TITLE
migratebundle: fix bundle migration when there are multiple elements in the placement clause

### PR DESCRIPTION
**Pull request by rogpeppe**
This fixes some of the recent openstack bundle problems.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1:

**Comment by urosj** [comment]
:+1: on code, but please do QA as discussed.

**Comment by frankban** [comment]
:+1: thank you!

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/20/
Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/21/
Test PASSed.

**Pull request merged**
