### PR TITLE
csclient: implement Publish

### PR DESCRIPTION
**Pull request by rogpeppe**
Also remove resources-related functionality from charmrepo.CharmRepo
and provide a Client method instead.

The main purpose of the top-level charmrepo package is to provide
the Interface abstraction. New functionality outside of that
should be implemented in csclient only.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1: impressive compression

**Comment by mattyw** [comment]
:+1:

**Comment by natefinch** [comment]
:+1:   though, you're gonna break my other branch again :/

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/210/
Test PASSed.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
