### PR TITLE
Update dependencies and fix some tests for mongo without js

### PR DESCRIPTION
**Pull request by wallyworld**
Use charm.v6-unstable with supported-series
Fix a test
Skip mongo tests which use js if no js

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/61/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM thanks

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
