### PR TITLE
Add terms1 and terms2 charms.

### PR DESCRIPTION
**Pull request by cmars**

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/145/
Test PASSed.

**Comment by urosj** [comment]
:+1:

**Comment by cmars** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
