### PR TITLE
Define parameters for setting an authorization cookie.

### PR DESCRIPTION
**Pull request by frankban**

### CODE REVIEW

**Comment by makyo** [comment]
:+1:

**Comment by jrwren** [comment]
:+1:

**Comment by fabricematrat** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/44/
Test PASSed.

**Comment by frankban** [comment]
Thank you all!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
