### PR TITLE
merge new-channels-model branch

### PR DESCRIPTION
**Pull request by rogpeppe**
No conflicts, no problem.

### CODE REVIEW

**Comment by rogpeppe** [comment]
:shipit:

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/199/
Test PASSed.

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
