### PR TITLE
csclient: use meta/resources, not meta/resource

### PR DESCRIPTION
**Pull request by rogpeppe**
The meta endpoint is /meta/resources, not /meta/resource.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/241/
Test PASSed.

**Comment by mhilton** [comment]
:+1:

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
