### PR TITLE
csclient/params: add Channel and PublishRequest

### PR DESCRIPTION
**Pull request by rogpeppe**
Also update the test that relies on the old publish endpoint.

### CODE REVIEW

**Comment by mhilton** [comment]
:+1:

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/168/
Test PASSed.

**Comment by frankban** [comment]
:+1:

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
