### PR TITLE
Propagate error causes when retrieving charms and bundles.

### PR DESCRIPTION
**Pull request by frankban**
Also update a test so that future regressions can be avoided.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/33/
Test PASSed.

**Comment by mhilton** [comment]
:+1: LGTM

**Comment by rogpeppe** [comment]
LGTM it makes me think that we should perhaps document the possible
error causes as part of the charmstore interface and propagate them
explicitly. That's something for later though.

**Comment by frankban** [comment]
Thanks for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
