### PR TITLE
remove origin from api struct, since it's never used.

### PR DESCRIPTION
**Pull request by natefinch**
It's misleading to have a value in the returned struct that will never be set.  Removing it would have made this bug exceedingly obvious.

This fixes https://bugs.launchpad.net/juju-core/+bug/1577415 - resource-get hangs when trying to deploy a charm with resource from the store

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/250/
Test PASSed.

**Comment by wallyworld** [comment]
LGTM

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Comment by urosj** [comment]
I think this merge brakes charm store.

**Comment by rogpeppe** [comment]
@urosj Charmstore still builds and test OK. Although I'm in general against backwardly incompatible changes even in "unstable" repos, this one seems to be OK.

**Comment by rogpeppe** [comment]
... and the Origin field really wanted to go anyway :)

**Pull request merged**
