### PR TITLE
001 legacy no escape v2 unstable

### PR DESCRIPTION
**Pull request by mhilton**
This is identical to https://github.com/juju/charmrepo/pull/38 but targeted at the unstable branch.

### CODE REVIEW

**Comment by rogpeppe** [comment]
LGTM

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/92/
Test FAILed.

**Comment by mhilton** [comment]
Note the test failure was spurious http://ci.jujugui.org:8080/job/charmrepo/94/ worked fine with the same branch.

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
