### PR TITLE
Service to application

### PR DESCRIPTION
**Pull request by wallyworld**
Bundles now have applications instead of services

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/256/
Test PASSed.

**Comment by perrito666** [comment]
shipit

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
