### PR TITLE
csclient: test everything against real charmstore code

### PR DESCRIPTION
**Pull request by rogpeppe**
This gives me a warm fuzzy feeling.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/243/
Test PASSed.

**Comment by ericsnowcurrently** [comment]
While I'm convinced that isolated unit tests are useful in their own right, I'm also fully in favor of having functional end-to-end tests, as you've added.  My strong preference would be to leave the unit tests, but I'd rather not get into a lengthy discussion right now about the merits of unit tests if that is what would happen. :)

So LGTM, with a dissenting vote on removing the unit tests.

**Comment by rogpeppe** [comment]
Tests are always a trade off between the confidence they give you that the
code is correct and the maintenance burden that the test code imposes. In
this case, I don't see that the deleted tests gave us any great confidence
that the code worked (it didn't) and the maintenence burden is significant
(less direct production code, tests with a non-obvious stubbing framework,
tests that rely directly on internal implementation details).

Where there's 100% overlap between test coverage, I much prefer to keep the
tests that give more confidence and throw away the others.

If there was any significant business logic in the code, I might feel
differently.

**Comment by frankban** [comment]
:+1: thank you!

**Comment by urosj** [comment]
👍

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
