### PR TITLE
update charm dependency; move to charmrepo.v2

### PR DESCRIPTION
**Pull request by rogpeppe**
Mostly automatic changes. The automated tests will fail on this branch because of the cyclic dependency with charmstore. Will manually verify that tests pass against charmstore before pushing the green button.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/107/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/108/
Test FAILed.

**Comment by mhilton** [comment]
:+1: with some nitpicks and you'll need to make jenkins happy

**Comment by rogpeppe** [comment]
Superceded by PR #46

**Pull request closed without merging**
