### PR TITLE
Update resource naming

### PR DESCRIPTION
**Pull request by Veebers**
Updates the use of resource types from docker to oci/container image.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmrepo/411/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmrepo/413/

**Comment by Veebers** [comment]
$$merge$$

**Comment by Veebers** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
