### PR TITLE
csclient: implement UploadResourceWithRevision

### PR DESCRIPTION
**Pull request by rogpeppe**
This provides a suitable client entry point for the newly added
PUT resource charmstore endpoint.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmrepo/418/

**Comment by mhemmings** [comment]
Shouldn't `UploadResourceWithRevision` and `ResumeUploadResourceWithRevision` have doc comments? Otherwise lgtm

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmrepo/419/

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
