### PR TITLE
migratebundle: handle exposing services

### PR DESCRIPTION
**Pull request by frankban**
Also update dependencies to use latest charm package.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/96/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:  Code :ok:

**Comment by rogpeppe** [comment]
LGTM thanks

**Comment by frankban** [comment]
Thank you both for the reviews!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
