### PR TITLE
allow upload of multi-series charms

### PR DESCRIPTION
**Pull request by mhilton**
Make sure charmrepo will attempt to upload a multi-series charm when asked.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/117/
Test PASSed.

**Comment by rogpeppe** [comment]
LGTM thanks

**Comment by frankban** [comment]
:+1: thank you!

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
