### PR TITLE
Add ReadBundleFile

### PR DESCRIPTION
**Pull request by wallyworld**
Add support for reading standalone bundle files.

### CODE REVIEW

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/87/
Test FAILed.

**Comment by axw** [comment]
LGTM, but it appears you've got an issue with dependencies.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/88/
Test PASSed.

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Comment by wallyworld** [comment]
:shipit:

**Pull request merged**
