### PR TITLE
migratebundle: fix migration error message

### PR DESCRIPTION
**Pull request by rogpeppe**

### CODE REVIEW

**Comment by urosj** [comment]
:+1: Thanks for the regression test.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmrepo/3/
Test PASSed.

**Comment by rogpeppe** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmrepo-merge

**Pull request merged**
