### PR TITLE
Forward-port changes from v3

### PR DESCRIPTION
**Pull request by achilleasa**
Forward port of the following PRs against the v3 branch:
- Add charmstore method to resolve charm/bundles with a preferred channel #153
- Allow client users to specify channel when querying metadata #154
- Additional ways to create a repo #156

### CODE REVIEW

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by achilleasa** [comment]
$$merge$$

**Comment by achilleasa** [comment]
$$merge$$

**Pull request merged**
